import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const sourceRoots=['src','scripts'];const files=[];for(const dirName of sourceRoots)walk(path.join(root,dirName));function walk(dir){for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const full=path.join(dir,entry.name);if(entry.isDirectory())walk(full,rootDir,locale);else files.push(full)}}
const errors=[];const importRe=/(?:import\s+[^'";]+?\s+from\s+|import\s*)['"](\.{1,2}\/[^'"]+)['"]/g;const extensions=['','.ts','.js','.mjs','.astro','.css','.svg','/index.ts','/index.js','/index.astro'];for(const file of files.filter(f=>/\.(astro|ts|js|mjs)$/.test(f))){const text=fs.readFileSync(file,'utf8');for(const match of text.matchAll(importRe)){const target=path.resolve(path.dirname(file),match[1]);if(!extensions.some(ext=>fs.existsSync(target+ext)))errors.push(`${path.relative(root,file)}: unresolved local import ${match[1]}`)}}
const required=['astro.config.mjs','src/content.config.ts','src/lib/i18n.mjs','src/lib/portal-content.ts','src/lib/current-portal-content.ts','src/components/LocaleSwitcher.astro','src/components/StarlightLanguageSwitcher.astro','src/components/pages/HomePage.astro','src/components/pages/QTablePage.astro','src/components/pages/QTableUIPage.astro','src/components/pages/RoadmapPage.astro','src/styles/portal-v2.css','src/styles/portal-v4.css','src/styles/starlight.css','src/pages/index.astro','src/pages/en/index.astro','src/pages/zh-tw/index.astro','src/pages/qtable.astro','src/pages/qtable-ui.astro','src/pages/examples.astro','src/pages/roadmap.astro','src/pages/404.astro','src/content/docs/docs/index.md','src/content/docs/en/docs/index.md','src/content/docs/zh-tw/docs/index.md','src/content/docs/docs/getting-started/production-checklist.md','src/content/docs/docs/project/feature-matrix.md','scripts/verify-i18n.mjs','scripts/verify-transfer-build.mjs','.github/workflows/ci.yml','.github/workflows/deploy.yml','public/favicon.svg','public/og.svg'];for(const rel of required)if(!fs.existsSync(path.join(root,rel)))errors.push(`missing required file: ${rel}`);
for(const file of files.filter(f=>/\.(astro|ts|js|mjs|css|md)$/.test(f))){const rel=path.relative(root,file);const text=fs.readFileSync(file,'utf8');if(!rel.startsWith('scripts/')&&/\b(TODO|FIXME)\b/i.test(text))errors.push(`${rel}: contains TODO/FIXME`);if(!rel.startsWith('scripts/')&&/boychina\/qingzonex\.github\.io/i.test(text))errors.push(`${rel}: hard-codes temporary repository owner/path`);if(rel.startsWith('src/')&&!rel.endsWith('portal-content.ts')&&/v0\.1\.0-alpha\b/.test(text))errors.push(`${rel}: contains stale v0.1.0-alpha version; current published source tag is v0.1.1-alpha`)}
const canonicalDocs=[...files.filter(f=>path.relative(root,f).replaceAll('\\','/').startsWith('src/content/docs/')&&/\.md$/.test(f)),path.join(root,'README.md'),path.join(root,'DEPLOYMENT.md')];for(const file of canonicalDocs){const rel=path.relative(root,file);const text=fs.readFileSync(file,'utf8');if(/github\.com\/QingZoneX\/QTable(?:UI)?(?:\b|\/)/.test(text))errors.push(`${rel}: links to retired QTable/QTableUI repository path; use qtable-server/qtable-web`);if(/QingZoneX\/QTableUI\b/.test(text)||/\bQTableUI\b/.test(text))errors.push(`${rel}: uses retired QTableUI repository name; use qtable-web or QTable Web App`);if(/TypeScript 6\b/.test(text))errors.push(`${rel}: documents stale TypeScript 6 frontend stack; qtable-web uses TypeScript 7`);if(/github\.com\/QingZoneX\/qtable-(?:server|web)\/issues\/\d+/i.test(text))errors.push(`${rel}: pins product documentation to a specific implementation issue; describe the product direction instead`)}
const site=fs.readFileSync(path.join(root,'src/lib/site.ts'),'utf8');if(!site.includes('https://github.com/QingZoneX/qtable-server')||!site.includes('https://github.com/QingZoneX/qtable-web'))errors.push('site.ts must expose canonical qtable-server and qtable-web repository URLs');
const layout=fs.readFileSync(path.join(root,'src/layouts/BaseLayout.astro'),'utf8');const navBlock=layout.match(/const nav\s*=\s*\[(.*?)\];/s)?.[1]||'';if(/qtable-ui/i.test(navBlock))errors.push('primary portal navigation must not expose QTableUI as a separate product');if(!layout.includes('portal-v4.css'))errors.push('BaseLayout must load the portal v4 visual system after existing brand styles');if(!layout.includes('QTABLE_UI_GITHUB_URL'))errors.push('BaseLayout footer must expose both QTable implementation repositories');
const home=fs.readFileSync(path.join(root,'src/components/pages/HomePage.astro'),'utf8');if(/href\(['"]qtable-ui\//i.test(home))errors.push('homepage must not link to QTableUI as a separate product page');for(const requiredClass of ['hero-v4','capability-layout','arch-pipeline','experience-grid'])if(!home.includes(requiredClass))errors.push(`homepage is missing required portal v4 composition: ${requiredClass}`);if(/TypeScript 6\b/.test(home))errors.push('homepage must reflect the current TypeScript 7 qtable-web stack');
const roadmap=fs.readFileSync(path.join(root,'src/components/pages/RoadmapPage.astro'),'utf8');if(/c\.(?:active|next)\.map/.test(roadmap)||/\/issues(?:\/|['"`])/.test(roadmap))errors.push('roadmap page must present durable product direction instead of issue-number-driven implementation lists');if(!roadmap.includes('architecture-showcase')||!roadmap.includes('copy.plans'))errors.push('roadmap page must include the QingZoneX/QTable product architecture and future planning themes');
const config=fs.readFileSync(path.join(root,'astro.config.mjs'),'utf8');if(/\{\s*label:\s*['"]QTableUI['"]\s*,\s*items:/s.test(config))errors.push('Starlight sidebar must not expose QTableUI as a separate product group');
const qtableUIPage=fs.readFileSync(path.join(root,'src/components/pages/QTableUIPage.astro'),'utf8');if(!qtableUIPage.includes("'qtable/'")||!qtableUIPage.includes('#frontend'))errors.push('legacy QTableUI page must redirect to the QTable frontend section');
if(errors.length){console.error(errors.join('\n'));process.exit(1)}console.log(`Source verification passed for ${files.length} project files with canonical qtable-server/qtable-web links, v0.1.1-alpha source-tag positioning, issue-number-independent roadmap/docs, single-product QTable positioning and portal v4 composition.`);
